// Copies the WOFF2 subsets CarbX ships out of the fontsource packages into
// public/fonts, and regenerates src/fonts.css from the packages' own
// unicode-range declarations so the ranges can never drift from the files.
//
//   npm run fonts
//
// Only latin, latin-ext and greek are shipped. Cyrillic and Vietnamese are
// dropped: the label parser reads English, Dutch, German, French and Greek.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";

const SUBSETS = ["latin", "latin-ext", "greek"];
const SANS = "node_modules/@fontsource-variable/source-sans-3";
const MONO = "node_modules/@fontsource/source-code-pro";

const faces = (cssPath) => {
  const css = readFileSync(cssPath, "utf8");
  const out = [];
  for (const m of css.matchAll(/@font-face\s*\{(.*?)\}/gs)) {
    const body = m[1];
    const file = body.match(/url\(\.\/files\/(.+?)\.woff2\)/);
    const range = body.match(/unicode-range:\s*([^;]+);/);
    const weight = body.match(/font-weight:\s*([^;]+);/);
    if (!file || !range) continue;
    const subset = SUBSETS.find((s) =>
      new RegExp(`-${s}-(wght|\\d{3})-`).test(file[1]));
    if (!subset || !SUBSETS.includes(subset)) continue;
    out.push({ file: file[1], range: range[1].trim(), weight: weight[1].trim(), subset });
  }
  return out;
};

mkdirSync("public/fonts", { recursive: true });
const blocks = [];
const emit = (family, dir, list, format) => {
  for (const f of list) {
    copyFileSync(`${dir}/files/${f.file}.woff2`, `public/fonts/${f.file}.woff2`);
    blocks.push(`@font-face {
  font-family: "${family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url("/fonts/${f.file}.woff2") format("${format}");
  unicode-range: ${f.range};
}`);
  }
};

emit("Source Sans 3 Variable", SANS, faces(`${SANS}/wght.css`), "woff2-variations");
emit("Source Code Pro", MONO, [...faces(`${MONO}/400.css`), ...faces(`${MONO}/500.css`)], "woff2");

writeFileSync("src/fonts.css", `/* Generated by scripts-fonts.mjs. Do not edit by hand.

   Self-hosted so the app renders identically on every device, and so no
   visitor's IP reaches a font CDN. Subsets are split by unicode-range, so a
   browser fetches the Greek face only when Greek is actually on the page and a
   Dutch-language session never downloads it.

   Source Sans 3 and Source Code Pro, SIL Open Font License 1.1. */

${blocks.join("\n")}
`);
console.log(`fonts: ${blocks.length} faces, ${SUBSETS.join(", ")}`);
